@startuml
'https://plantuml.com/sequence-diagram

class App{
    main()
    start()
}

class AppController{
    - mainList: ArrayList<List>
    - taskSelected: ChoiceBox
    - listScreen: TreeView<String>
    - initialize()

    + menuButtonPressed(actionEvent: ActionEvent)
    + taskCompletedButtonPressed(actionEvent: ActionEvent)
    + showAllTasksSelected(actionEvent: ActionEvent)
    + showCompletedTasksSelected(actionEvent: ActionEvent)
    + showUncompletedTasksSelected(actionEvent: ActionEvent)

}

class List{
    - title: String
    - taskList: ArrayList<Task>

    + getTitle(): String
    + setTitle(title: String)
    + addTask(dueDate: String, description: String)
    + getTask(index: int): Task
}

class menuController{

    - editDescription: boolean
    - ETEditedDescription: TextField
    - ETUserMessage: TextArea
    - ATSelectedList: ChoiceBox
    - ATSelectedDate: DatePicker
    - ATEnteredDescription: TextField
    - ATUserMessage: TextArea
    - ILFilePath: TextField
    - ILUserMessage: TextArea
    - SLFilePath: TextField
    - SLUserMessage: TextArea
    - initialize()
    - refresh()

    + okButtonPressed(actionEvent: ActionEvent)
    + editDescriptionChecked(actionEvent: ActionEvent)
    + editDueDateChecked(actionEvent: ActionEvent)
    + updateTaskButtonPressed(actionEvent: ActionEvent)
    + addTaskButtonPressed(actionEvent: ActionEvent)
    + scanListButtonPressed(actionEvent: ActionEvent)
    + saveListButtonPressed(actionEvent: ActionEvent)
}

class Task{
    - dueDate: String
    - description: String
    - completed: boolean

    + getDueDate(): String
    + setDueDate(dueDate: String)
    + getDescription(): String
    + setDescription(description: String)
    + getCompleted(): boolean
    + setCompleted(completed: boolean)
}

javafx.Application <|-- App

App -  AppController
AppController - menuController
List - Task
@enduml