@startuml
'https://plantuml.com/sequence-diagram

class App{
    main()
    start()
}

class AppController{
    - mainList: List
    - viewControl: int
    - taskTable: TableView<Task>
    - completedColumn: TableColumn<Task, String>
    - dueDateColumn: TableColumn<Task, String>
    - descriptionColumn: TableColumn<Task, String>
    - dueDateField: DatePicker
    - description: TextField

    + showAllTasksSelected(actionEvent: ActionEvent)
    + showCompletedTasksSelected(actionEvent: ActionEvent)
    + showUncompletedTasksSelected(actionEvent: ActionEvent)
    + menuButtonPressed(actionEvent: ActionEvent)
    + dueDateEditAsserted(actionEvent: ActionEvent)
    + descriptionEditAsserted(actionEvent: ActionEvent)
    + completeTaskButtonPressed(actionEvent: ActionEvent)
    + incompleteTaskButtonPressed(actionEvent: ActionEvent)
    + removeTaskButtonPressed(actionEvent: ActionEvent)
    + clearListButtonPressed(actionEvent: ActionEvent)
    + createTaskButtonPressed(actionEvent: ActionEvent)
    + createNewTask(newDueDate: String, newDescription: String)
    + setTasksComplete(selectedTasks ObservableList<Task>, complete: boolean)
    + clearList()
    + setAppMainList(newList: List)
    + updateTable()
    + getAllTaskInfo()
    + initialize()

}

class List{
    - taskList: ArrayList<Task>

    + addTask(completed: String, dueDate: String, description: String)
    + getTask(index: int): Task
    + findTask(description: String): int
    + getTaskListSize(): int
    + removeTask(index: int)
}

class menuController{

    - mainList: List
    - ILFilePath: TextField
    - ILUserMessage: TextArea
    - SLFilePath: TextField
    - SLUserMessage: TextArea

    + okButtonPressed(actionEvent: ActionEvent)
    + setMenuMainList(newList: List)
    + scanListButtonPressed(actionEvent: ActionEvent)
    + saveListButtonPressed(actionEvent: ActionEvent)
}

class Task{
    - dueDate: String
    - description: String
    - completed: String

    + getDueDate(): String
    + setDueDate(dueDate: String)
    + getDescription(): String
    + setDescription(description: String)
    + getCompleted(): boolean
    + setCompleted(completed: boolean)
}

javafx.Application <|-- App

App -  AppController
AppController - menuController
List - Task
@enduml